name: Docs

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3

      # - name: Install nightly toolchain
      #   uses: dtolnay/rust-toolchain@master
      #   with:
      #     toolchain: nightly
      #     components: clippy, rustfmt
      #     targets: wasm32-unknown-unknown

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build docs
        run: |
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo doc --no-deps --workspace

      - name: Deploy
        # if: github.event_name == 'push' # FIXME: Uncomment before release
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
