[package]
name = "app"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
app-io = { path = "io" }
gstd = { git = "https://github.com/gear-tech/gear" }
gmeta = { git = "https://github.com/gear-tech/gear" }
hashbrown = "0.13"

[build-dependencies]
app-io = { path = "io" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear" }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear" }
gstd = { git = "https://github.com/gear-tech/gear", features = ["debug"] }
tokio = "1"
gclient = { git = "https://github.com/gear-tech/gear" }

[features]
binary-vendor = []

[workspace]
members = ["state"]
